pull_request_rules:
  - name: Merge Mine
    conditions:
      - and:
          - author~=^bengosney$
          - check-success=test
          - check-success=Sourcery
    actions:
      merge:
        method: merge

  - name: Automatic merge dependabot PR
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=test
    actions:
      merge:
        method: merge

  - name: Automatic merge on approval of Sourcery AI PR
    conditions:
      - author~=^sourcery.*$
      - check-success=test
    actions:
      merge:
        method: merge