[project]
name = "SEO Tool"
version = "2.0.0"
description = "Pluing based SEO Reporting Tool"
authors = [
    "Ben Gosney <bengosney@googlemail.com>"
]
python = "^3.7"
repository = "https://github.com/bengosney/stretchtheirlegs/"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 188
target-version = ['py37']

[tool.pycln]
all = true
